In [1]:
#import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [4]:
df=pd.read_csv("/content/sonar data.csv",header=None)
# here we took header=None because there is no any header

In [5]:
df.head()

       0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [6]:
df.describe()

               0           1           2   ...          57          58          59
count  208.000000  208.000000  208.000000  ...  208.000000  208.000000  208.000000
mean     0.029164    0.038437    0.043832  ...    0.007949    0.007941    0.006507
std      0.022991    0.032960    0.038428  ...    0.006470    0.006181    0.005031
min      0.001500    0.000600    0.001500  ...    0.000300    0.000100    0.000600
25%      0.013350    0.016450    0.018950  ...    0.003600    0.003675    0.003100
50%      0.022800    0.030800    0.034300  ...    0.005800    0.006400    0.005300
75%      0.035550    0.047950    0.057950  ...    0.010350    0.010325    0.008525
max      0.137100    0.233900    0.305900  ...    0.044000    0.036400    0.043900

[8 rows x 60 columns]

In [35]:
df.shape

(208, 61)

In [9]:
df[60].value_counts()
#here we see that total no of M and R

M    111
R     97
Name: 60, dtype: int64

In [10]:
"""split data in to X and y
   here we see that 61 columns out of which we took 1st 60 coumns in X and 
   last column in y as we want to predict the output...axis=1 means columns and axis =0 means row
   """

X=df.drop(columns=60,axis=1)
y=df[60]

In [13]:
#train test split 

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [14]:
#Bulid the model and find the accuracy
# for fiting the data into model we always use X_train and y_train

lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
#predict the model
#for predict the model we use X_test only
pred=lr.predict(X_test)
pred

array(['M', 'R', 'R', 'M', 'R', 'R', 'R', 'R', 'M', 'R', 'M', 'M', 'M',
       'M', 'M', 'M', 'R', 'M', 'M', 'R', 'M', 'R', 'M', 'R', 'M', 'M',
       'R', 'M', 'R', 'M', 'M', 'M', 'M', 'R', 'R', 'R', 'R', 'R', 'R',
       'M', 'M', 'M', 'R', 'M', 'M', 'M', 'M', 'R', 'M', 'M', 'R', 'M',
       'R', 'R', 'M', 'M', 'M', 'R', 'R', 'R', 'M', 'M', 'M'],
      dtype=object)

In [27]:
#find Accuracy of the model
acc=lr.score(X_test,y_test)
print("The Model Accuracy is",acc) #so your model gives 77 % accuracy

The Model Accuracy is 0.7777777777777778

In [34]:
"""Make Predictive system
Here we took 1st row in data set as input and that input conveted into array
and that array stored in one object.We took reshape because we are predicting 
for one instance and finally simply predicted that object and printed 
the value .we have found the result M.M means object is Mine.
"""
data=(0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.0660,0.2273,0.3100,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.5550,0.6711,0.6415,0.7104,0.8080,0.6791,0.3857,0.1307,0.2604,0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.0510,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032)
X=np.asarray(data)
Xreshape=X.reshape(1,-1)
pred=lr.predict(Xreshape)

print(pred)

['M']

In [32]:
if (pred=='M'):
  print("The object is Mine")
else:
  print("The object is Rock")

The object is Mine